package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePatienthistory<M extends BasePatienthistory<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setZhenduan(java.lang.String zhenduan) {
		set("zhenduan", zhenduan);
	}

	public java.lang.String getZhenduan() {
		return get("zhenduan");
	}

	public void setZhusu(java.lang.String zhusu) {
		set("zhusu", zhusu);
	}

	public java.lang.String getZhusu() {
		return get("zhusu");
	}

	public void setZkjc(java.lang.String zkjc) {
		set("zkjc", zkjc);
	}

	public java.lang.String getZkjc() {
		return get("zkjc");
	}

	public void setZlfs(java.lang.String zlfs) {
		set("zlfs", zlfs);
	}

	public java.lang.String getZlfs() {
		return get("zlfs");
	}

	public void setImg(java.lang.String img) {
		set("img", img);
	}

	public java.lang.String getImg() {
		return get("img");
	}

	public void setJws(java.lang.String jws) {
		set("jws", jws);
	}

	public java.lang.String getJws() {
		return get("jws");
	}

	public void setPatientid(java.lang.String patientid) {
		set("patientid", patientid);
	}

	public java.lang.String getPatientid() {
		return get("patientid");
	}

	public void setDepartmentid(java.lang.String departmentid) {
		set("departmentid", departmentid);
	}

	public java.lang.String getDepartmentid() {
		return get("departmentid");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

}
