package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePatientrecord<M extends BasePatientrecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSfmode(java.lang.Integer sfmode) {
		set("sfmode", sfmode);
	}

	public java.lang.Integer getSfmode() {
		return get("sfmode");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setFs(java.lang.String fs) {
		set("fs", fs);
	}

	public java.lang.String getFs() {
		return get("fs");
	}

	public void setIstrue(java.lang.Integer istrue) {
		set("istrue", istrue);
	}

	public java.lang.Integer getIstrue() {
		return get("istrue");
	}

	public void setPatientid(java.lang.String patientid) {
		set("patientid", patientid);
	}

	public java.lang.String getPatientid() {
		return get("patientid");
	}

	public void setDepartmentid(java.lang.String departmentid) {
		set("departmentid", departmentid);
	}

	public java.lang.String getDepartmentid() {
		return get("departmentid");
	}

	public void setStime(java.util.Date stime) {
		set("stime", stime);
	}

	public java.util.Date getStime() {
		return get("stime");
	}

}
