package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePatientinfo<M extends BasePatientinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setAge(java.lang.String age) {
		set("age", age);
	}

	public java.lang.String getAge() {
		return get("age");
	}

	public void setNumber(java.lang.String number) {
		set("number", number);
	}

	public java.lang.String getNumber() {
		return get("number");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setMarryed(java.lang.String marryed) {
		set("marryed", marryed);
	}

	public java.lang.String getMarryed() {
		return get("marryed");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setReimbursement(java.lang.String reimbursement) {
		set("reimbursement", reimbursement);
	}

	public java.lang.String getReimbursement() {
		return get("reimbursement");
	}

	public void setDepartmentid(java.lang.String departmentid) {
		set("departmentid", departmentid);
	}

	public java.lang.String getDepartmentid() {
		return get("departmentid");
	}

	public void setDoct(java.lang.String doct) {
		set("doct", doct);
	}

	public java.lang.String getDoct() {
		return get("doct");
	}

	public void setZhenduan(java.lang.String zhenduan) {
		set("zhenduan", zhenduan);
	}

	public java.lang.String getZhenduan() {
		return get("zhenduan");
	}

	public void setZhusu(java.lang.String zhusu) {
		set("zhusu", zhusu);
	}

	public java.lang.String getZhusu() {
		return get("zhusu");
	}

	public void setZkjc(java.lang.String zkjc) {
		set("zkjc", zkjc);
	}

	public java.lang.String getZkjc() {
		return get("zkjc");
	}

	public void setZlfs(java.lang.String zlfs) {
		set("zlfs", zlfs);
	}

	public java.lang.String getZlfs() {
		return get("zlfs");
	}

	public void setImg0(java.lang.String img0) {
		set("img0", img0);
	}

	public java.lang.String getImg0() {
		return get("img0");
	}

	public void setImg1(java.lang.String img1) {
		set("img1", img1);
	}

	public java.lang.String getImg1() {
		return get("img1");
	}

	public void setImg2(java.lang.String img2) {
		set("img2", img2);
	}

	public java.lang.String getImg2() {
		return get("img2");
	}

	public void setJws(java.lang.String jws) {
		set("jws", jws);
	}

	public java.lang.String getJws() {
		return get("jws");
	}

	public void setZltime(java.util.Date zltime) {
		set("zltime", zltime);
	}

	public java.util.Date getZltime() {
		return get("zltime");
	}

}
