package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDepartment<M extends BaseDepartment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setReimbursementname(java.lang.String reimbursementname) {
		set("reimbursementname", reimbursementname);
	}

	public java.lang.String getReimbursementname() {
		return get("reimbursementname");
	}

	public void setReimbursementuser(java.lang.String reimbursementuser) {
		set("reimbursementuser", reimbursementuser);
	}

	public java.lang.String getReimbursementuser() {
		return get("reimbursementuser");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setPower(java.lang.String power) {
		set("power", power);
	}

	public java.lang.String getPower() {
		return get("power");
	}

}
