package com.demo.common.model;

import com.demo.common.model.base.BaseDepartment;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Department extends BaseDepartment<Department> {
	public static final Department dao = new Department();
	
	public Record checkAdmin(String user,String pwd){
		Record r = Db.findFirst("select * from department where reimbursementuser=? and password=?",user,pwd);
		return r;
	}
}
