package com.demo.common.model;

import com.demo.common.model.base.BaseInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Info extends BaseInfo<Info> {
	public static final Info dao = new Info();
}
