package com.demo.common.model;

import com.demo.common.model.base.BasePatientinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Patientinfo extends BasePatientinfo<Patientinfo> {
	public static final Patientinfo dao = new Patientinfo();
}
