package com.demo.common.model;

import com.demo.common.model.base.BasePatientrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Patientrecord extends BasePatientrecord<Patientrecord> {
	public static final Patientrecord dao = new Patientrecord();
}
