package com.demo.common.model;

import com.demo.common.model.base.BasePatienthistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Patienthistory extends BasePatienthistory<Patienthistory> {
	public static final Patienthistory dao = new Patienthistory();
}
