package com.demo.common.model;

import com.demo.common.model.base.BaseReimbursement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Reimbursement extends BaseReimbursement<Reimbursement> {
	public static final Reimbursement dao = new Reimbursement();
}
